# Generated by Django 3.2.2 on 2021-08-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emppersonal',
            name='profile_pic',
            field=models.FileField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='emppersonal',
            name='per_email',
            field=models.CharField(max_length=30),
        ),
    ]
